// -*- C++ -*- generated by wxGlade 0.6.3 on Thu Apr 03 11:24:46 2008

#include <wx/wx.h>
#include <wx/image.h>
#include <wx/cmdline.h>
// begin wxGlade: ::dependencies
// end wxGlade


#ifndef MAIN_H
#define MAIN_H


// begin wxGlade: ::extracode
// end wxGlade

// ----------------------------------------------------------------------------
// constants
// ----------------------------------------------------------------------------

// control ids
enum
{
    Stratlas_Quit = 1,
    Stratlas_About,
    Stratlas_Settings,
    Stratlas_Help,
    Stratlas_Clear,
    Stratlas_Add,
    Stratlas_Remove,
    Stratlas_Process,
    Stratlas_Worklist,
    Stratlas_Filelist
};

// Define a new application type, each program should derive a class from wxApp
class StratlasApp : public wxApp
{
public:
    // override base class virtuals
    // ----------------------------

    // this one is called on application startup and is a good place for the app
    // initialization (doing it here and not in the ctor allows to have an error
    // return: if OnInit() returns false, the application terminates)
    virtual bool OnInit();
    // custom command line parser
    virtual void OnInitCmdLine(wxCmdLineParser& parser);
    virtual bool OnCmdLineParsed(wxCmdLineParser& parser);
private:
    bool silent_mode;
};

static const wxCmdLineEntryDesc g_cmdLineDesc [] =
{
     { wxCMD_LINE_SWITCH, wxT("h"), wxT("help"), wxT("displays help on the command line parameters"),
          wxCMD_LINE_VAL_NONE, wxCMD_LINE_OPTION_HELP },
     { wxCMD_LINE_SWITCH, wxT("s"), wxT("silent"), wxT("disables the GUI") },
 
     { wxCMD_LINE_NONE }
};

DECLARE_APP(StratlasApp)

// frame stuff

class MyFrame: public wxFrame {
public:
    // begin wxGlade: MyFrame::ids
    // end wxGlade

    MyFrame(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_FRAME_STYLE);

private:
    // begin wxGlade: MyFrame::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: MyFrame::attributes
    wxListBox* list_box_1;
    wxButton* button_1;
    wxButton* button_2;
    wxListBox* list_box_2;
    wxButton* button_3;
    wxButton* button_4;
    wxMenuBar* frame_1_menubar;
    wxStatusBar* frame_1_statusbar;
    // end wxGlade
    
    // event handlers
    void OnButtonClear(wxCommandEvent& event);
    void OnButtonAdd(wxCommandEvent& event);
    void OnButtonRemove(wxCommandEvent& event);
    void OnButtonProcess(wxCommandEvent& event);

    void OnMenuQuit(wxCommandEvent& event);
    void OnMenuSettings(wxCommandEvent& event);
    void OnMenuAbout(wxCommandEvent& event);
    void OnMenuHelp(wxCommandEvent& event);

    void OnWorklist(wxCommandEvent& event);
    void OnFilelist(wxCommandEvent& event);

private:

    // helper protos
    void UpdateFileList(char *);
    
    char path[1024];

    char output_format[8];

    // any class wishing to process wxWidgets events must use this macro
    DECLARE_EVENT_TABLE()
}; // wxGlade: end class

#endif // MAIN_H
